name: "Detect Environment"
description: "Detect the environment based on the branch and event context"
outputs:
  environment:
    description: "The detected environment"

runs:
  using: "composite"
  steps:
    - name: Detect Environment
      id: detect-env
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          ENVIRONMENT="${{ github.event.inputs.environment }}"
        else
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            if [[ "${{ github.event.action }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
              BRANCH_NAME="${{ github.base_ref }}"
            else
              BRANCH_NAME="${{ github.head_ref }}"
            fi
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi

          case "$BRANCH_NAME" in
            "main")
              ENVIRONMENT="production"
              ;;
            "release")
              ENVIRONMENT="preprod"
              ;;
            "dev")
              if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                ENVIRONMENT="stage"
              else
                ENVIRONMENT="dev"
              fi
              ;;
            *)
              ENVIRONMENT="dev"
              ;;
          esac
        fi

        echo "Detected environment: $ENVIRONMENT"
        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
