name: "Detect Environment"
outputs:
  environment:
    description: "The detected environment"
    value: ${{ steps.detect-env.outputs.environment }}

runs:
  using: "composite"
  steps:
    - name: Detect Environment
      id: detect-env
      shell: bash
      run: |
        ENVIRONMENT="Environment"

        echo "Detected environment: $ENVIRONMENT"
        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
