name: Distribute Demo

on:
  pull_request:
    types: [closed]
    branches:
      - demo
  push:
    branches:
      - demo

jobs:
  demo:
    uses: ./.github/workflows/distribute.yml
    with:
      scheme: "Demo"
    secrets: inherit
