name: Pushed to dev

on:
  push:
    branches:
      - dev

jobs:
  distribute:
    name: Distribute to Dev
    uses: ./.github/workflows/distribute.yml
    with:
      scheme: "Dev"
    secrets: inherit
