name: PR closed

on:
  pull_request:
    types: 
      - closed
    branches:
      - dev

jobs:
  distribute:
    if: github.event.pull_request.merged == true
    name: Distribute to Stage
    uses: ./.github/workflows/distribute.yml
    with:
      scheme: "Stage"
    secrets: inherit
