name: PR updated on dev

on:
  pull_request:
    types: 
      - synchronize
      - opened
      - reopened
    branches:
      - dev

jobs:
  distribute:
    name: Distribute to Dev
    uses: ./.github/workflows/distribute.yml
    with:
      scheme: "Dev"
    secrets: inherit
