name: Distribute Dev

on:
  push:
    branches:
      - dev
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  dev:
    uses: ./.github/workflows/distribute.yml
    with:
      scheme: "Some"
    secrets: inherit
