name: Distribute Demo

on:
  push:
    branches:
      - demo
  workflow_dispatch:
    branches:
      - demo

jobs:
  demo:
    uses: ./.github/workflows/distribute_reusable.yml
    with:
      scheme: "Demo"
    secrets: inherit
