on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string

jobs:
  distribute:
    name: Distribute
    runs-on: macos-12
    env:
      BUILD_DIR: ${{ './build' }}
      SCHEME: ${{ inputs.scheme }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Distribute Test
        run: |
          echo "Test logs"
          
          echo "Branch is ${GITHUB_BASE_REF}"
          echo "Scheme is ${SCHEME}"
