name: Distribute Prod

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  prod:
    uses: ./.github/workflows/distribute.yml
    with:
      scheme: "Production"
    secrets: inherit
